# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdd2fdb9a5f74aec8ff74188a781ce9f49137aa64b7cf5bde48477a3ea1ef296943daf5f52dea5a7199cb3e735816f6448c407ed562b2f597ee9c4aa2a5c9551

test:
  secret_key_base: 5807fb5b0df9697ad65a0e9e09615878966af0fb5470d2da0e8734f1c1b955591f7af854686b6afb938287712ed22210bcbf8414b430f080ea36b35b758e11a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
